config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/help'

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }
	validates :password, presence: true, length: { minimum: 8 }
	validates :username, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to @user
		else
			render 'new'
		end
	end

	def update
	end

	def destroy
	end

private
	def user_params
		params.require(:user).permit(:username, :password, :email)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper

	 # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Surf Trends"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default" role="navigation">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to "Surf Trends", root_path, class: "navbar-brand" %>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li><%= link_to "About", static_pages_about_path %></li>
	        <li><%= link_to "Help", static_pages_help_path %></li>
	      </ul>
	      <ul class="nav navbar-nav navbar-right">
	        <li><%= link_to 'Sign Up', new_user_path %></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
	          <ul class="dropdown-menu" role="menu">
	            <li><a href="#">Action</a></li>
	            <li><a href="#">Another action</a></li>
	            <li><a href="#">Something else here</a></li>
	            <li class="divider"></li>
	            <li><a href="#">Separated link</a></li>
	          </ul>
	        </li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
	<div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>A place where surfers can broadcast post-session conditions so other surfers can get real-time updates as to how conditions are developing.</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>If you need help please contact us at help@surftrends.com</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
  <h1>Surf Trends</h1>

  <h2>
    This is the home page for the Surf Trends application.  Think Waze for surfing conditions.
  </h2>

  <%= link_to "Place A Report", '#', class: "btn btn-large btn-primary" %>
  <%= link_to "Check Reports", '#', class: "btn btn-large btn-primary" %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
	
	<%= f.label :username %>
	<%= f.text_field :username %>
	<%= f.label :email %>
	<%= f.text_field :email %>
	<%= f.label	:password %>
	<%= f.password_field :password %>
	<%= f.label	:confirm_password %>
	<%= f.password_field :confirm_password %>
	<%= f.submit %>
		
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up For An Account</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title, 'User Profile') %>
<h1>Profile</h1>
<p><%= @user.username %></p>
<p><%= @user.email %></p>